### ISSUE TITLE
markdown 表格问题

### ISSUE THREAD

**Issue by Suomea** [TMaize/tmaize-blog#10]
![Capture](https://user-images.githubusercontent.com/26758537/91651011-ac5f5680-eab9-11ea-8f91-027b1a055c64.PNG)
表格的渲染好像有点问题。

**Comment by TMaize** [comment]
你的markdown语法有问题，第二行的横杆怎么有长有短

**Comment by Suomea** [comment]
> 你的markdown语法有问题，第二行的横杆怎么有长有短  

![Capture](https://user-images.githubusercontent.com/26758537/91651501-0fec8280-eac0-11ea-8d3f-9cdd045a2067.PNG)
这是源代码和渲染出来后的效果。
```text
-----------------  
| 序号 |   书名   |   作者  |  状态  |    
| ----: | ----: | ----: | ----: |    
| 1 | 《Spring Cloud 微服务实战》 | 翟永超 | 进行中 |  
| 2 | 《C 程序设计语言·第二版》 |  Brian W. Kernighan、Dennis M. Ritchie | 进行中 |  
```

**Comment by TMaize** [comment]
分割线和表格之间留个空行就行了，github pages的markdown的格式有点严格，尽量写的规范

**Comment by Suomea** [comment]
> 分割线和表格之间留个空行就行了，github pages的markdown的格式有点严格，尽量写的规范
