### ISSUE TITLE
暗黑模式

### ISSUE THREAD

**Issue by maoruibin** [TMaize/tmaize-blog#11]
作者有没有考虑过支持暗黑模式？😊

**Comment by TMaize** [comment]
我明天加上

**Comment by TMaize** [comment]
> 作者有没有考虑过支持暗黑模式？😊

我明天加上

**Comment by maoruibin** [comment]
> > 作者有没有考虑过支持暗黑模式？😊
> 
> 我明天加上

棒，期待~    https://gudong.site/

**Comment by TMaize** [comment]
> > > 作者有没有考虑过支持暗黑模式？😊
> > 
> > 
> > 我明天加上
> 
> 棒，期待~ https://gudong.site/

调好了，目前是跟随系统的，还差一个页面上的开关。样式参照的是GitHub的夜间模式

**Comment by maoruibin** [comment]
![Screenshot_2021-01-05-12-17-20-790_com android chrome](https://user-images.githubusercontent.com/3887626/103605881-04b6d100-4f50-11eb-822a-5979a742e729.jpg)

good，🥰🥰  开关可以慢慢来 ……
