### ISSUE TITLE
为什么H1、H2标题渲染不出来

### ISSUE THREAD

**Issue by burning846** [TMaize/tmaize-blog#13]
如题

**Comment by get2333** [comment]
可以正常渲染。

如果不想看到 #  号，把 post.css 中的以下 css 删去

```
.page-post .post h1::before,
.page-post .post h2::before {
  content: '#';
  top: 0;
  font-weight: bold;
  padding-right: 6px;
}
```

**Comment by burning846** [comment]
> 可以正常渲染。
> 
> 如果不想看到 # 号，把 post.css 中的以下 css 删去
> 
> ```
> .page-post .post h1::before,
> .page-post .post h2::before {
>   content: '#';
>   top: 0;
>   font-weight: bold;
>   padding-right: 6px;
> }
> ```

所以原来前面的#是个feature……所以只要魔改`post.css`就可以改成我想要的格式了对吧
