### ISSUE TITLE
请问如何部署在VPS？

### ISSUE THREAD

**Issue by KawausoJyou** [TMaize/tmaize-blog#23]
很喜欢您的主题，但我尝试部署在VPS中失败了。

**Comment by TMaize** [comment]
VPS 安装 WordPress、Typecho 写博客不是更好吗

**Comment by KawausoJyou** [comment]
> VPS 安装 WordPress、Typecho 写博客不是更好吗

😂哈哈，好吧，打扰了。
已经找到基于Hexo与您的主题一样简洁的主题了。
