### ISSUE TITLE
为啥添加公式后页面间距变得不正常了？

### ISSUE THREAD

**Issue by CaiJi-bai** [TMaize/tmaize-blog#24]

**Comment by TMaize** [comment]
有链接吗，我看下没问题的

![微信图片_20220424192846](https://user-images.githubusercontent.com/16556693/164974399-3731a0c2-1f94-42c4-8d5c-b244c06298ac.png)

**Comment by CaiJi-bai** [comment]
我看了一下，用$$来表示公式就会出现用`\( \)`就好了。

**Comment by CaiJi-bai** [comment]
我看了一下，用$$来表示公式就会出现间距不正常，用`\( \)`就好了。

**Comment by CaiJi-bai** [comment]
有什么解决办法吗？

**Comment by TMaize** [comment]
我用两种表示都是正常的，[你点这里看下](https://blog.tmaize.net/posts/2015/01/01/%E4%B8%BB%E9%A2%98%E9%A2%84%E8%A7%88.html#数学公式)

**Comment by CaiJi-bai** [comment]
重要的是得有``,麻烦你了，谢谢
