### ISSUE TITLE
暗黑模式点击链接会先闪一下白色再变成黑色

### ISSUE THREAD

**Issue by mingkwind** [TMaize/tmaize-blog#27]
有点不适，能不能优化一下

**Comment by TMaize** [comment]
我这边测试是好的，没这个问题

**Comment by Pathsis** [comment]
> 我这边测试是好的，没这个问题

在Chrome上测试，会有闪烁的“掉帧”过渡，感觉对眼睛不是很友好😄

**Comment by mingkwind** [comment]
> 我这边测试是好的，没这个问题
![Jul-17-2022 16-36-29](https://user-images.githubusercontent.com/72091562/179390644-0fda2b4f-6b6f-4d78-a141-ecbd27e423c7.gif)

**Comment by Pathsis** [comment]
> > 我这边测试是好的，没这个问题
> > ![Jul-17-2022 16-36-29](https://user-images.githubusercontent.com/72091562/179390644-0fda2b4f-6b6f-4d78-a141-ecbd27e423c7.gif)
> >       
> >         [
> >           
> >             ![Jul-17-2022 16-36-29](https://user-images.githubusercontent.com/72091562/179390644-0fda2b4f-6b6f-4d78-a141-ecbd27e423c7.gif)
> >           
> >         ](https://user-images.githubusercontent.com/72091562/179390644-0fda2b4f-6b6f-4d78-a141-ecbd27e423c7.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/72091562/179390644-0fda2b4f-6b6f-4d78-a141-ecbd27e423c7.gif)

我说的就是这个效果😄

**Comment by Pathsis** [comment]
我说的就是这个闪烁效果。

**Comment by TMaize** [comment]
@mingkwind 这是什么浏览器

**Comment by mingkwind** [comment]
> @mingkwind 这是什么浏览器

macos的chrome
