### ISSUE TITLE
iOS下点击搜索框缩放问题

### ISSUE THREAD

**Issue by Pathsis** [TMaize/tmaize-blog#28]
我猜测是因为搜索框的字体小于16px，导致点击搜索的输入框导致需要缩放，可以优化下哈

**Comment by TMaize** [comment]
@Pathsis 能帮忙截个图吗，我没有iOS设备😅

**Comment by Pathsis** [comment]
> @Pathsis 能帮忙截个图吗，我没有iOS设备😅


https://user-images.githubusercontent.com/72077265/179390076-048dea58-0542-41da-9408-cb4858cdb8fb.MP4

如果输入框的字体大于等于16px，则应该不会缩放了。这似乎是IOS的“陈年规定”。

**Comment by TMaize** [comment]
已更新
