### ISSUE TITLE
iframe中使用网易云音乐type=0的外链时无法成功加载网页

### ISSUE THREAD

**Issue by Limpu403** [TMaize/tmaize-blog#30]
代码如下
<iframe src="//music.163.com/outchain/player?type=0&id=6725259483&auto=0&height=500" frameborder="0" width="520px" height="520px"></iframe> 

![F92CD678-2ABC-40EB-BA2A-F3A005E799D6](https://user-images.githubusercontent.com/81900789/181678739-121ec8a3-2b9a-4522-82bd-90d9c6fed527.jpeg)

效果可至[此处](https://limpu403.github.io/posts/2035-01-01-曲集.html)查看

![9A98FC06-D01B-4071-AFE4-214CF5DAC187](https://user-images.githubusercontent.com/81900789/181678766-a2ac55ad-33b6-467a-a317-1d6fad249d82.jpeg)

望提供解决方案

**Comment by TMaize** [comment]
@Limpu403 你好，感谢反馈，[这个歌单 6725259483](https://music.163.com/#/outchain/0/6725259483/) 貌似是登录后才可查看

所以无法播放

**Comment by Limpu403** [comment]
居然是歌单权限的问题😭，感谢解答
