### ISSUE TITLE
有没有办法做页面浏览量，显示在文章页

### ISSUE THREAD

**Issue by pansong291** [TMaize/tmaize-blog#32]

**Comment by TMaize** [comment]
有，可以用这个免费的服务

[不蒜子](https://busuanzi.ibruce.info/)

**Comment by TMaize** [comment]
代码已提交，配置 extCount: true开启

需要自定义可参考 [改动的代码](https://github.com/TMaize/tmaize-blog/commit/dace07bdf4f71b9bbcb3dfbc19bc4ea16833f4a4)

默认样式如下

![image](https://user-images.githubusercontent.com/16556693/216886252-ba106ce0-5196-436a-9d8e-6bb2ebf5fd34.png)

![image](https://user-images.githubusercontent.com/16556693/216886277-b04066fd-c16e-4042-a9c9-6bded664ad67.png)
