### ISSUE TITLE
文章链接的相关问题

### ISSUE THREAD

**Issue by YuanJ2003** [TMaize/tmaize-blog#34]
请问作者，文章链接如何更改为使用slug作为永久链接？并且文章的文件名开头不写时间的话，如何把文章显示出来，并且如何通过md文件中的date来获取日期呢？

**Comment by TMaize** [comment]
名字必须按照规定的格式来 [creating-posts](https://jekyllrb.com/docs/posts/#creating-posts)

设置永久链接修改 _config.yml 文件

```
permalink: /post/:name.html
```

或者为某个文章单独设置

```
---
title: post title
permalink: xxxx
---
```
