### ISSUE TITLE
你的全文检索是什么原理呢？我想给我的博客加一个全文检索的功能

### ISSUE THREAD

**Issue by Darian1996** [TMaize/tmaize-blog#6]
你的全文检索是什么原理呢？我想给我的博客加一个全文检索的功能

**Comment by TMaize** [comment]
参考下面两个文件
static/js/search.js
static/xml/search.xml

**Comment by Darian1996** [comment]
blog.addxxx()

blog 是什么？

**Comment by TMaize** [comment]
定义的一个全局变量，里面有一些常用方法static/js/blog.js
