### ISSUE TITLE
请问如何修改baseurl才能让这个博客出现子目录？

### ISSUE THREAD

**Issue by thejiangcj** [TMaize/tmaize-blog#7]
如题，感谢您的网站，不过我由于已经使用了1个主页作为网站，但我在我原来主页设置“blog”超链接时发现链接不能很好跳转，请问这方面该如何解决？

baseurl: '/blog'

这是我baseurl的设置

**Comment by TMaize** [comment]
能贴个链接吗，我没懂你的意思

**Comment by thejiangcj** [comment]
抱歉，设置问题，已解决
