### ISSUE TITLE
清空目录和删除目录应该没区别叭？

### ISSUE THREAD

**Issue by yueyinqiu** [TMaize/tmaize-blog#8]
![image](https://user-images.githubusercontent.com/18749772/87290350-7cbbb580-c530-11ea-985c-3b4389575bb1.png)
这个意思应该是说让它为空叭？但是git好像是不会包含空目录的。

**Comment by TMaize** [comment]
我的意思是把我写的文章和引用的图片删除




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TMaize/tmaize-blog"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月13日(星期一) 下午5:45
收件人:&nbsp;"TMaize/tmaize-blog"<tmaize-blog@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[TMaize/tmaize-blog] 清空目录和删除目录应该没区别叭？ (#8)





 

 这个意思应该是说让它为空叭？但是git好像是不会包含空目录的。
